name: quizzical
description: "A Flutter Trivia Application."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.13.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  shared_preferences: ^2.5.5
  html_unescape: ^2.0.0
  google_fonts: ^8.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
